### PR TITLE
fix: get /wallets returns correct pagination

### LINKED ISSUE #419: GET `/wallets` returns wrong pagination parameters
The endpoint returns wrong `total` field.

### PR DESCRIPTION
**Pull request by pranavkparti**
## Description
GET `/wallets` returns the correct `total` field in the response object. 

**Issue(s) addressed**
- Resolves #419.

**What kind of change(s) does this PR introduce?**

- [ ] Enhancement
- [X] Bug fix
- [ ] Refactor

**Please check if the PR fulfils these requirements**

- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**
The `total` currently returned is the same as the `limit` parameter. It should be the total number of objects that match the input parameters instead.

**What is the new behavior?**
The `total` field returns the correct value.

## Breaking change

**Does this PR introduce a breaking change?**
No.

## Other useful information
None.

### CODE REVIEW

File: server/repositories/WalletRepository.js [hunk 1]
```diff
@@ -107,11 +110,10 @@ class WalletRepository extends BaseRepository {
     }
 
     const wallets = await query;
-    if (getCount) {
-      const count = await this._session.getDB().from(query.as('p')).count('*');
+    Joi.assert(wallets, Joi.array().required());
```
Comment (Kpoke) [inline server/repositories/WalletRepository.js:113]: This is not needed

File: server/repositories/WalletRepository.js [hunk 2]
```diff
@@ -98,6 +98,9 @@ class WalletRepository extends BaseRepository {
 
     query = query.union(union1, union2);
 
+    // get the total count (before applying limit and offset options)
+    const count = await this._session.getDB().from(query.as('p')).count('*');
```
Comment (Kpoke) [inline server/repositories/WalletRepository.js:102]: if getCount is false, I don't want us making this extra call. We can set this query at this point without a limit attached to it to a variable and not call it, and then call it using await in the if(getCount) statement

**Review by Kpoke — CHANGES_REQUESTED** [review]
