### PR TITLE
Fix limit for routes 2

### LINKED ISSUE #186: Sweep limit, offset parameters for all endpoints
The implementation of limit and offset parameters for all endpoints needs to be checked and corrected in several ways.

(1) Some endpoints have in memory limit,offset logic implemented, instead limit and offset should use the build in LIMIT and OFFSET functionalities of SQL, using knex.

(2) All endpoints should have min (0) and max (1000) parameters for limit, and a min parameter of 0 for offset.  Offset should default to 0, and limit should default to the max of 1000.

(3) Additionally the following issues need to be checked and resolved if work is still needed.

https://github.com/Greenstand/treetracker-wallet-api/issues/185
https://github.com/Greenstand/treetracker-wallet-api/issues/183
https://github.com/Greenstand/treetracker-wallet-api/issues/87

### LINKED ISSUE #191: Shouldn't restrict the max start parameter.
https://github.com/Greenstand/treetracker-wallet-api/blob/807e09d275d052f43c666ec0fe8de9ebeddb8255/server/routes/tokenRouter.js#L89

https://github.com/Greenstand/treetracker-wallet-api/blob/807e09d275d052f43c666ec0fe8de9ebeddb8255/server/routes/tokenRouter.js#L46

I think we shouldn't restrict the maximum start value to 10000 right?

### PR DESCRIPTION
**Pull request by zo-chu**
- fixes some offsets and limits for transfer api and other minor issues
- lint

partially fixes #186
fixes #191

### CODE REVIEW

File: server/routes/walletRouter.js [hunk 1]
```diff
@@ -17,7 +17,7 @@ walletRouter.get('/',
       req.query,
       Joi.object({
         limit: Joi.number().required(),
-        start: Joi.number().min(1).max(10000).integer(),
+        start: Joi.number().min(1).integer(),
```
Comment (dadiorchen) [inline server/routes/walletRouter.js:20]: Thank you for remove these unnecessary code.

**Review by dadiorchen — APPROVED** [review]
