### PR TITLE
fix: transfer request claim is optional parameter

### LINKED ISSUE #409: `POST /transfers` transfer request schema claim field must be optional
The transfer request must have `claim` as an optional parameter, as pointed out by @sebastiangaertner .

### PR DESCRIPTION
**Pull request by pranavkparti**
## Description
The endpoint `POST /transfers` takes in `claim` as optional parameter. The functionality behind claiming a token is not yet implemented however. 

**Issue(s) addressed**
- Resolves #409 

**What kind of change(s) does this PR introduce?**
- [ ] Enhancement
- [X] Bug fix
- [ ] Refactor

**Please check if the PR fulfils these requirements**
- [X] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## Issue

**What is the current behavior?**
The transfer request schema validation checks for the claim parameter, which it shouldn't do.

**What is the new behavior?**
Claim is optional, with a default value of `false`

## Breaking change

**Does this PR introduce a breaking change?**
No.

## Other useful information
None.

### CODE REVIEW

File: server/handlers/transferHandler/schemas.js [hunk 1]
```diff
@@ -12,16 +12,15 @@ const transferPostSchema = Joi.alternatives()
...
+        claim: Joi.boolean().default(false),
       }),
       otherwise: Joi.object({
         bundle: Joi.object({
           bundle_size: Joi.number().min(1).max(10000).integer(),
         }).required(),
         sender_wallet: Joi.string().required(),
         receiver_wallet: Joi.string().required(),
-        claim: Joi.boolean().required(),
+        claim: Joi.boolean().default(false),
```
Comment (Kpoke) [inline server/handlers/transferHandler/schemas.js:23]: Don't think this default will work, due to the way we are calling the validations with validateAsync. Can you confirm this?

Comment (pranavkparti) [reply server/handlers/transferHandler/schemas.js:23]: You are right. The claim value would just be left undefined in this case. I've fixed it.
